name: "ğŸ”” Release"
# author: "Julius Haas <juliushaas91@gmail.de>"

on:
  workflow_dispatch:

jobs:
  check-branch:
    name: "ğŸ” Check current branch"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸš« Terminate if workflow is not running on 'main'"
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Releases are only supported from the main branch. Stopping execution."
          exit 1

  release:
    name: "ğŸ”” Run Release"
    runs-on: ubuntu-latest
    needs: check-branch
    concurrency: release

    permissions:
      id-token: write
      contents: write
      actions: write

    steps:
      - name: "ğŸ”„ Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "ğŸ“¦ Setup Project Environment"
        uses: ./.github/actions/setup-project-environment

      - name: "ğŸš¦Validate Code"
        uses: ./.github/actions/lint-format-test-code

      - name: "ğŸ” Load ENV variables"
        uses: ./.github/actions/load-env-variables
        with:
          env-file: './config.env'

      - name: "ğŸ”¢ Run Semantic Release"
        uses: python-semantic-release/python-semantic-release@v10.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: ${{ env.GIT_COMMITTER_NAME }}
          git_committer_email: ${{ env.GIT_COMMITTER_EMAIL }}

# NOTE: uncomment this if you want to deploy a new version after the release automatically
#      - name: "ğŸš€ Deploy to Google Cloud"
#        uses: ./.github/actions/deploy-to-gcloud
